### ISSUE TITLE
As a Customer I want to be able to see from my shopping list what is available at the store so that I know what to buy at the LGL

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#12]
# Description of issue
display what you are unable to buy on the recipe at the store 
- [x] #161
- [x] #162
- [x] #163

# Definition of done
- [x] requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed

**Comment by jaibeer72** [comment]
done
