### ISSUE TITLE
As an Admin I want to be able to schedule recipes to be featured weekly so that I don't need to manually feature them every week

### ISSUE THREAD

**Issue by caydey** [AgileGroup6/Agile-Project#126]
# Description of issue
After communication with the client, she express how she would like the ability schedule what recipes should be on the featured list

# Back-end
- [x] #147
- [x] #153
- [x] #167 
- [x] #168
# Front-end
- [x] #139
- [x] #148
- [x] #150
- [x] #186
- [x] #192
- [x] #193

# Definition of done
- [x] requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed

**Comment by davidtopping02** [comment]
featured recipe implemented
