### ISSUE TITLE
As a customer I want to be able to access the web app from a scannable QR code so that the web app is easy to find

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#127]
# Description of issue
- [x] #136
- [x] #137
- [x] #138

# Definition of done
- [x] requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed

**Comment by davidtopping02** [comment]
story is complete
