### ISSUE TITLE
As a user I want recipes to be recommended based off what I have in my shopping list, so that I can get ideas for things to cook

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#14]
# Description of issue
search recipes that have items from the shopping list

# Front-end
- [ ] ...

# Back-end
- [x] #44
- [x] #43
- [x] #63

# Definition of done
- [ ] requirements for this issue to be marked as completed
- [ ] Follows the colour scheme
- [ ] Code is well commented
- [ ] Tests have been completed

**Comment by davidtopping02** [comment]
issue completed
