### ISSUE TITLE
As a store owner, I want an allergy notice so that my Customers are aware of any possible allergens in products

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#17]
# Description of issue
- [x] #155
- [x] #156
- [x] #157

# Definition of done
- [x] requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed

**Comment by FinnHagan** [comment]
All completed as per description of issue and definition of done.
