### ISSUE TITLE
As a store owner I want to introduce pre-build tests so that I can make sure the data integrity of my website is maintained

### ISSUE THREAD

**Issue by jaibeer72** [AgileGroup6/Agile-Project#203]
Description of issue

# On commits or before commits the test are ran to make sure the ingredients stores are not brokenn

# Tests to be added 
- [x] test for ingredients store

# Definition of done

- [x] requirements for this issue to be marked as completed
- [ ] Follows the colour scheme
- [ ] Code is well commented
- [ ]Tests have been complete

**Comment by davidtopping02** [comment]
tests implemented
