### ISSUE TITLE
As a customer I would like to be able browse all ingredients section so that I can find ingredients to add to my shopping list

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#21]
# Description of issue
this is having a view all section for the ingredients where you can manually search through products, preferably done in categories
# Front End
- [x] #59
- [x] #60
- [x] #71
# Back End
- [x] #61
- [x] #62
# Definition of done
 Requirements for this issue to be marked as completed
- [x] All buttons and menus are functional
- [x] Database is properly queried and returns correct results
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed

**Comment by davidtopping02** [comment]
story completed
