### ISSUE TITLE
shopping list bug coming from browse all ingredients

### ISSUE THREAD

**Issue by davidtopping02** [AgileGroup6/Agile-Project#215]
# Description of issue
The shopping list changes size coming from the browse all page to the home page

# Definition of done
- [x] Requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed
- [x] Run `npm run build` after front end changes

**Comment by calebh210** [comment]
Fixed with #230
