### ISSUE TITLE
browse all ingredients sometimes not loading

### ISSUE THREAD

**Issue by davidtopping02** [AgileGroup6/Agile-Project#216]
# Description of issue
sometimes the browse all ingredients/recipes is not loading correctly when landing on the specific pages

# Definition of done
- [x] Requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed
- [x] Run `npm run build` after front end changes

**Comment by calebh210** [comment]
Could not replicate, closing
