### ISSUE TITLE
BrowseAllRecipe scalable images.

### ISSUE THREAD

**Issue by kekizl** [AgileGroup6/Agile-Project#256]
# Description of issue

Fix bug that recipes are taking up more than the phone screen.

# Definition of done
- [ ] Requirements for this issue to be marked as completed
- [ ] Follows the colour scheme
- [ ] Code is well commented
- [ ] Tests have been completed
- [ ] Run `npm run build` after front end changes

**Comment by caydey** [comment]
closed by #257
