### ISSUE TITLE
As a store owner I want to add my own recipes so that I can continuously update the recipe repository

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#9]
# Description of issue
from the admin page have a form that connects to the database and is capable of adding all the information that is required in recipes

# Front End
- [x] #103
- [x] #104
- [x] #105

# Back End
- [x] Authenticate user before upload
- [x] Create API endpoint to save recipe to database

# Definition of done
- [x] requirements for this issue to be marked as completed
- [x] Follows the colour scheme
- [x] Code is well commented
- [x] Tests have been completed

**Comment by davidtopping02** [comment]
completed, moving for push to main
